MODEL_CONFIGS = {
    "h5m80d50_priority": {
        "signal_file": "h5priority_target.csv",
        "signal_dir": "signals_h5priority",
        "file_glob": "signals_h5m80d50_priority_*.csv",
        "date_regex": r"^signals_h5m80d50_priority_(\d{8})\.csv$",
        "priority_name_column": "priority_name",
        "priority_mapping": {
            "P1": 1,
            "P1A_current_consensus": 1, 
            "P1B_low_turnover_exception": 1, 
            "P2_current_broader": 2,
            "avg_top1|avg_top3": 2,
            "avg_top1|avg_top3|vote3_top3": 2,
            "P3_global_china_expansion": 3,
        },
        "horizon": 5,
        "gain": 8.0,
        "cut": -5.0,
    },
    "h2m80d50_dual": {
        "signal_file": "h2dual_target.csv",
        "signal_dir": "signals_h2dual",
        "file_glob": "signals_*.csv",
        "date_regex": r"^signals_(\d{8})\.csv$",
        "priority_name_column": "signal_layer",
        "priority_mapping": {
            "overlap_core": 1,
            "strong_only": 2,
            "strict_only": 3,
            "layer2_m1_only": 5,
            "layer2_m1_m3_overlap": 5, 
            "layer2_m3_only": 5, 
        },
        "horizon": 2,
        "gain": 8.0,
        "cut": -5.0,
    },
    "h5m80d50_ensemble": {
        "signal_file": "h5ensemble_target.csv",
        "signal_dir": "signals_h5ensemble",
        "file_glob": "signals_*.csv",
        "date_regex": r"^signals_(\d{8})\.csv$",
        "priority_name_column": "signal_tag",
        "priority_mapping": {
            "F220_TOP1_LATE_EARLY_GATE": 1,
            "F220_TOP1_LATE_EARLY_GATE|CONSENSUS_3": 1,
            "F220_TOP1_LATE_EARLY_GATE|CONSENSUS_2": 1,
            "F220_TOP1_LATE_EARLY_GATE|FAMILY_ONLY": 1,
            "CONSENSUS_3": 1,
            "CONSENSUS_2": 2,
            "FAMILY_ONLY": 3,
        },
        "horizon": 5,
        "gain": 8.0,
        "cut": -5.0,
    },
}
